name: scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3 * * 1'

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    if: ${{ github.event.repository.private == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@ff5dd8929f96a8a4dc67d13f32b8c75057829621 # v2.4.0
        continue-on-error: true
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false
      - uses: github/codeql-action/upload-sarif@e8e8e51caba890f74f97e228d00b0b81b666ee4c # v3
        if: ${{ github.event.repository.private == false && hashFiles('results.sarif') != '' }}
        continue-on-error: true
        with:
          sarif_file: results.sarif
